// Code generated by protoc-gen-go. DO NOT EDIT.
// source: frametracker.proto

package frametracker

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	States               []*Status `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	LastReceive          int64     `protobuf:"varint,2,opt,name=last_receive,json=lastReceive,proto3" json:"last_receive,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6ec844a93fa6f21, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetStates() []*Status {
	if m != nil {
		return m.States
	}
	return nil
}

func (m *Config) GetLastReceive() int64 {
	if m != nil {
		return m.LastReceive
	}
	return 0
}

type Status struct {
	TimeLastSync         int64    `protobuf:"varint,1,opt,name=time_last_sync,json=timeLastSync,proto3" json:"time_last_sync,omitempty"`
	TokenHash            string   `protobuf:"bytes,2,opt,name=token_hash,json=tokenHash,proto3" json:"token_hash,omitempty"`
	NewestFile           string   `protobuf:"bytes,3,opt,name=newest_file,json=newestFile,proto3" json:"newest_file,omitempty"`
	NewestFileDate       int64    `protobuf:"varint,4,opt,name=newest_file_date,json=newestFileDate,proto3" json:"newest_file_date,omitempty"`
	DropboxError         string   `protobuf:"bytes,5,opt,name=dropbox_error,json=dropboxError,proto3" json:"dropbox_error,omitempty"`
	DropboxFailure       string   `protobuf:"bytes,6,opt,name=dropbox_failure,json=dropboxFailure,proto3" json:"dropbox_failure,omitempty"`
	Origin               string   `protobuf:"bytes,7,opt,name=origin,proto3" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6ec844a93fa6f21, []int{1}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetTimeLastSync() int64 {
	if m != nil {
		return m.TimeLastSync
	}
	return 0
}

func (m *Status) GetTokenHash() string {
	if m != nil {
		return m.TokenHash
	}
	return ""
}

func (m *Status) GetNewestFile() string {
	if m != nil {
		return m.NewestFile
	}
	return ""
}

func (m *Status) GetNewestFileDate() int64 {
	if m != nil {
		return m.NewestFileDate
	}
	return 0
}

func (m *Status) GetDropboxError() string {
	if m != nil {
		return m.DropboxError
	}
	return ""
}

func (m *Status) GetDropboxFailure() string {
	if m != nil {
		return m.DropboxFailure
	}
	return ""
}

func (m *Status) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

type StatusRequest struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6ec844a93fa6f21, []int{2}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

func (m *StatusRequest) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type StatusResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6ec844a93fa6f21, []int{3}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Config)(nil), "frametracker.Config")
	proto.RegisterType((*Status)(nil), "frametracker.Status")
	proto.RegisterType((*StatusRequest)(nil), "frametracker.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "frametracker.StatusResponse")
}

func init() { proto.RegisterFile("frametracker.proto", fileDescriptor_e6ec844a93fa6f21) }

var fileDescriptor_e6ec844a93fa6f21 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x4f, 0xe3, 0x30,
	0x10, 0xc5, 0x37, 0xdb, 0xdd, 0xac, 0x3a, 0x4d, 0xb3, 0x95, 0x41, 0xc8, 0xe2, 0x8f, 0x28, 0x01,
	0x89, 0x1e, 0x50, 0x0f, 0xe5, 0xcc, 0x09, 0xa8, 0x90, 0xe0, 0x94, 0x72, 0xe1, 0x14, 0xb9, 0xe9,
	0xa4, 0xb5, 0x9a, 0xc6, 0xc5, 0x9e, 0x14, 0xfa, 0xe5, 0x11, 0x8a, 0x9d, 0x8a, 0x22, 0x55, 0x1c,
	0xfd, 0x9b, 0xf7, 0xde, 0xd8, 0x4f, 0x06, 0x96, 0x69, 0xb1, 0x40, 0xd2, 0x22, 0x9d, 0xa3, 0xee,
	0x2f, 0xb5, 0x22, 0xc5, 0x82, 0x6d, 0x16, 0xbd, 0x80, 0x7f, 0xab, 0x8a, 0x4c, 0x4e, 0xd9, 0x15,
	0xf8, 0x86, 0x04, 0xa1, 0xe1, 0x5e, 0xb7, 0xd1, 0x6b, 0x0d, 0xf6, 0xfb, 0xdf, 0xcc, 0x23, 0x12,
	0x54, 0x9a, 0xb8, 0xd6, 0xb0, 0x33, 0x08, 0x72, 0x61, 0x28, 0xd1, 0x98, 0xa2, 0x5c, 0x21, 0xff,
	0xdd, 0xf5, 0x7a, 0x8d, 0xb8, 0x55, 0xb1, 0xd8, 0xa1, 0xe8, 0xc3, 0x03, 0xdf, 0xb9, 0xd8, 0x05,
	0x84, 0x24, 0x17, 0x98, 0x58, 0x8b, 0x59, 0x17, 0x29, 0xf7, 0xac, 0x3e, 0xa8, 0xe8, 0x93, 0x30,
	0x34, 0x5a, 0x17, 0x29, 0x3b, 0x01, 0x20, 0x35, 0xc7, 0x22, 0x99, 0x09, 0x33, 0xb3, 0x89, 0xcd,
	0xb8, 0x69, 0xc9, 0x83, 0x30, 0x33, 0x76, 0x0a, 0xad, 0x02, 0xdf, 0xd0, 0x50, 0x92, 0xc9, 0x1c,
	0x79, 0xc3, 0xce, 0xc1, 0xa1, 0xa1, 0xcc, 0x91, 0xf5, 0xa0, 0xb3, 0x25, 0x48, 0x26, 0x82, 0x90,
	0xff, 0xb1, 0x7b, 0xc2, 0x2f, 0xd5, 0x9d, 0x20, 0x64, 0xe7, 0xd0, 0x9e, 0x68, 0xb5, 0x1c, 0xab,
	0xf7, 0x04, 0xb5, 0x56, 0x9a, 0xff, 0xb5, 0x61, 0x41, 0x0d, 0xef, 0x2b, 0xc6, 0x2e, 0xe1, 0xff,
	0x46, 0x94, 0x09, 0x99, 0x97, 0x1a, 0xb9, 0x6f, 0x65, 0x61, 0x8d, 0x87, 0x8e, 0xb2, 0x03, 0xf0,
	0x95, 0x96, 0x53, 0x59, 0xf0, 0x7f, 0x76, 0x5e, 0x9f, 0xa2, 0x1b, 0x68, 0xd7, 0xad, 0xe1, 0x6b,
	0x89, 0x86, 0x36, 0x15, 0x97, 0xc6, 0x3e, 0xff, 0xc7, 0x8a, 0x4b, 0x13, 0x75, 0x20, 0xdc, 0xd8,
	0xcd, 0x52, 0x15, 0x06, 0x07, 0x63, 0xd8, 0x1b, 0x56, 0x86, 0x67, 0x67, 0x18, 0xa1, 0x5e, 0xc9,
	0x14, 0xd9, 0x23, 0x04, 0x31, 0xa6, 0x4a, 0x4f, 0xea, 0xb6, 0x8f, 0x76, 0xc6, 0xba, 0x3b, 0x1c,
	0x1e, 0xef, 0x1e, 0xba, 0x0d, 0xd1, 0xaf, 0xb1, 0x6f, 0x7f, 0xc9, 0xf5, 0x67, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x58, 0x5c, 0x0c, 0xcc, 0x3b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FrameTrackerServiceClient is the client API for FrameTrackerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FrameTrackerServiceClient interface {
	RecordStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type frameTrackerServiceClient struct {
	cc *grpc.ClientConn
}

func NewFrameTrackerServiceClient(cc *grpc.ClientConn) FrameTrackerServiceClient {
	return &frameTrackerServiceClient{cc}
}

func (c *frameTrackerServiceClient) RecordStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/frametracker.FrameTrackerService/RecordStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FrameTrackerServiceServer is the server API for FrameTrackerService service.
type FrameTrackerServiceServer interface {
	RecordStatus(context.Context, *StatusRequest) (*StatusResponse, error)
}

func RegisterFrameTrackerServiceServer(s *grpc.Server, srv FrameTrackerServiceServer) {
	s.RegisterService(&_FrameTrackerService_serviceDesc, srv)
}

func _FrameTrackerService_RecordStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrameTrackerServiceServer).RecordStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frametracker.FrameTrackerService/RecordStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrameTrackerServiceServer).RecordStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FrameTrackerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "frametracker.FrameTrackerService",
	HandlerType: (*FrameTrackerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordStatus",
			Handler:    _FrameTrackerService_RecordStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "frametracker.proto",
}
